name: groveman_crashlytics
description: Groveman tree that sends its logs to Firebase Crashlytics through recordError and logs.
version: 1.0.1
homepage: https://github.com/kmartins/groveman
repository: https://github.com/kmartins/groveman/tree/main/packages/groveman_crashlytics
issue_tracker: https://github.com/kmartins/groveman/issues
documentation: https://github.com/kmartins/groveman/tree/main/packages/groveman_crashlytics

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  firebase_crashlytics: ^3.1.1
  flutter:
    sdk: flutter
  groveman: ^1.2.1

dev_dependencies:
  firebase_core: ^2.10.0
  firebase_core_platform_interface: ^4.6.0
  firebase_crashlytics_platform_interface: ^3.4.1
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  stack_trace: ^1.10.0
