name: groveman_crashlytics
description: Groveman tree that sends its logs to Firebase Crashlytics through recordError and logs.
version: 1.0.2
homepage: https://github.com/kmartins/groveman
repository: https://github.com/kmartins/groveman/tree/main/packages/groveman_crashlytics
issue_tracker: https://github.com/kmartins/groveman/issues
documentation: https://github.com/kmartins/groveman/tree/main/packages/groveman_crashlytics
topics:
  - log
  - logger
  - logging
  - crashlytics
  - report
  - error

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_crashlytics: ^4.0.1
  flutter:
    sdk: flutter
  groveman: ^1.2.2

dev_dependencies:
  firebase_core: ^3.1.0
  firebase_core_platform_interface: ^5.1.0
  firebase_crashlytics_platform_interface: ^3.6.37
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  stack_trace: ^1.11.0
