name: groveman_crashlytics
description: Groveman tree that sends its logs to Firebase Crashlytics through recordError and logs.
version: 1.0.6
homepage: https://github.com/kmartins/groveman
repository: https://github.com/kmartins/groveman/tree/main/packages/groveman_crashlytics
issue_tracker: https://github.com/kmartins/groveman/issues
documentation: https://github.com/kmartins/groveman/tree/main/packages/groveman_crashlytics
topics:
  - log
  - logger
  - logging
  - crashlytics
  - report

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_crashlytics: ^5.0.7
  flutter:
    sdk: flutter
  groveman: ^1.2.5

dev_dependencies:
  firebase_core: ^4.4.0
  firebase_core_platform_interface: ^6.0.2
  firebase_crashlytics_platform_interface: ^3.8.17
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  stack_trace: ^1.12.1
