name: groveman_crashlytics
description: Groveman tree that sends your logs to Firebase Crashlytics.
version: 1.0.0
homepage: https://github.com/kmartins/groveman
repository: https://github.com/kmartins/groveman/tree/main/packages/groveman_crashlytics

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  firebase_crashlytics: ^2.4.4
  flutter:
    sdk: flutter
  groveman: ^1.1.0

dev_dependencies:
  firebase_core: ^1.10.6
  flutter_test:
    sdk: flutter
  lint: ^1.8.1
  stack_trace: ^1.10.0
