name: groveman_sentry
description: Groveman tree that sends its logs to Sentry.io through Breadcrumbs and events capture.
version: 1.0.1
homepage: https://github.com/kmartins/groveman
repository: https://github.com/kmartins/groveman/tree/main/packages/groveman_sentry
issue_tracker: https://github.com/kmartins/groveman/issues
documentation: https://github.com/kmartins/groveman/tree/main/packages/groveman_sentry

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  groveman: ^1.2.1
  meta: ^1.7.0
  sentry: ^7.4.2

dev_dependencies:
  lint: ^1.10.0
  test: ^1.21.1
