name: groveman_sentry
description: Groveman tree that sends its logs to Sentry.io through Breadcrumbs and events capture.
version: 1.0.1
homepage: https://github.com/kmartins/groveman
repository: https://github.com/kmartins/groveman/tree/main/packages/groveman_sentry
issue_tracker: https://github.com/kmartins/groveman/issues
documentation: https://github.com/kmartins/groveman/tree/main/packages/groveman_sentry
topics:
  - log
  - logger
  - logging
  - sentry
  - report
  - error

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  groveman: ^1.2.1
  meta: ^1.9.1
  sentry: ^7.6.3

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.3
