name: groveman_crashlytics_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  groveman: ^1.2.1
  groveman_crashlytics:
    path: ../

dev_dependencies:
  lint: ^2.1.2

flutter:
  uses-material-design: true
