name: groveman
description: Logging for Dart/Flutter applications, with the same concepts for tree and planting logging tree as Timber on Android
version: 1.0.0
homepage: https://github.com/kmartins/groveman

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.3
  mocktail: ^0.1.4
  test: ^1.17.0
