name: groveman
description: Logging for Dart/Flutter applications, with the same concepts for tree and planting logging tree as Timber on Android
version: 1.2.1
homepage: https://github.com/kmartins/groveman
repository: https://github.com/kmartins/groveman/tree/main/packages/groveman
topics:
  - log
  - logging
  - timber
  - report
  - error

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lint: ^2.1.2
  mocktail: ^0.3.0
  test: ^1.24.3
